name: mini.parser
version: 0.1.0
description: Parser for web-pages
author: <Vostrikov Vitaliy> <rasart.pro@gmail.com>
homepage: https://github.com/Rasarts/mini.parser
dependencies:
  http: any
  html: any
